#docker-compose.yml

#version: '' # Especifica  la versión del formato de archivos Compose

services:
  #Servicio 1: La BD
  db:
  # 1. IMAGEN: Usar la iIMG oficial ligera de PostgreSQL 14
    image: postgres:14-alpine # Usa una imagen preconstruida de Docker Hub

  # 2. NOMBRE: Nombre predecible al conyenedor
    container_name: spif_pg_db_v14

  # 3. REINICIO: Asegurar que se reinicie si el servidor se apaga
    restart: always

  # 4. CREDENCIALES
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: spif
      POSTGRES_PASSWORD: Vale#98z # ¡Asegúrate de que coincida con tu setting.py!

  # 5. PUERTOS: Mapeo Externo:Interno (el puerto 5433 es el que debe abrir)
    ports:
      - "5433:5432"

  # 6 PERSISTENCIAS DE DATOS: Usa el volumen definido abajo
    volumes:
      - spif_vol_db_data:/var/lib/postgresql/data # Persistencia de datos

  # 7. CHEQUEO DE SALUD: Verifica que el servidor Postgres esté listo antes de ser usado.
  healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spif"] # Puedes volver a usar CMD-SHELL
      interval: 5s
      timeout: 5s  # ¡Inclúyelo! Tu V2 lo acepta.
      retries: 5

  # 8. DEFINICIÓN DE VOLUMEN: El volumen real que persisten los datos en el servidor.
volumes:
  spif_vol_db_data: # Define el volumen para la BD