#docker-compose.yml

#version: '' # Especifica  la versión del formato de archivos Compose

services:
  #Servicio 1: El backend o la App Web
  web:
    build: . #  Le dices a Docker que busque un Dockerfile en este mismo directorio 
    ports:
      - "5433:5432" # Mapea el puerto 5432 del contenedor al puerto 5434 de tu servidor

    # Service 2: La BD
  db:
    image: postgres:14-alpine # Usa una imagen preconstruida de Docker Hub
    environment:
      POSTGRES_DB: spif_bd
      POSTGRES_USER: spif
      POSTGRES_PASSWORD: Vale#98z
    volumes:
      - spif_vol_db_data:/var/lib/postgresql/data # Persistencia de datos

volumes:
  spif_vol_db_data: # Define el volumen para la BD