services:
  # Servicio 1: La BD
  db:
    # 1. IMAGEN: Usar la iIMG oficial ligera de PostgreSQL 14
    image: postgres:14-alpine # Usa una imagen preconstruida de Docker Hub

    # 2. NOMBRE: Nombre predecible al contenedor
    container_name: spif_pg-v14
    
    # 3. REINICIO: Asegurar que se reinicie si el servidor se apaga
    restart: always

    # 4. CREDENCIALES
    environment:
      POSTGRES_DB: spif
      POSTGRES_USER: spif_user
      POSTGRES_PASSWORD: temporal

    # 5. PUERTOS: Mapeo Externo:Interno (el puerto 5435 es el que debe abrir)
    ports:
      - "5434:5432"

    # 6 PERSISTENCIAS DE DATOS: Usa el volumen definido abajo
    volumes:
      - vol_db_data:/var/lib/postgresql/data # Persistencia de datos

    # 7. CHEQUEO DE SALUD: Verifica que el servidor Postgres esté listo
    healthcheck: # <-- Alinear con 'image', 'ports', 'volumes', etc.
      test: ["CMD-SHELL", "pg_isready -U spif"] # <-- Cuatro espacios (anidado bajo healthcheck)
      interval: 5s
      timeout: 5s
      retries: 5

# 8. DEFINICIÓN DE VOLUMEN: El volumen real que persisten los datos en el servidor.
volumes:
  vol_db_data: # Define el volumen para la BD