# Generated by Django 5.2.6 on 2026-01-14 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False, verbose_name='ID Proveedor')),
                ('num_empleado', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('proveedor', models.CharField(max_length=100, null=True, verbose_name='Nombre Proveedor')),
                ('nombre_comercial', models.CharField(max_length=100, null=True)),
                ('rfc', models.CharField(max_length=20, null=True)),
                ('tipo', models.TextField(choices=[('', ''), ('BECARIO', 'BECARIO'), ('CONTRATISTA', 'CONTRATISTA'), ('DAP', 'DAP'), ('EMPLEADO', 'EMPLEADO'), ('ORGANISMOS', 'ORGANISMOS'), ('PAGO PASIVO', 'PAGO PASIVO'), ('PAGO UNICO', 'PAGO UNICO'), ('PROVEEDORES', 'PROVEEDORES'), ('SEGURO VIDA', 'SEGURO VIDA')], default=' ', max_length=50, null=True, verbose_name='Tipo Proveedor')),
                ('forma_pago', models.IntegerField(null=True)),
                ('banco', models.IntegerField(null=True)),
                ('banco_cuenta', models.CharField(max_length=20, null=True)),
                ('banco_tipo_cuenta', models.CharField(max_length=20, null=True)),
                ('fecha_alta', models.DateTimeField(max_length=23, null=True)),
                ('usuario_alta', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('fecha_modificacion', models.DateTimeField(max_length=23, null=True)),
                ('usuario_modificacion', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('estatus', models.CharField(choices=[('A', 'A'), ('C', 'C')], default='A', max_length=1, verbose_name='Estatus')),
                ('fecha_estatus', models.DateTimeField(max_length=23, null=True)),
                ('cuenta_pago', models.IntegerField(null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio_2', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(max_length=100, null=True)),
                ('observaciones', models.CharField(max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('pais', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=10, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('area_fax', models.CharField(max_length=10, null=True)),
                ('fax', models.CharField(max_length=50, null=True)),
                ('telefono_2', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('temporal', models.CharField(max_length=1, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, max_length=23, null=True, verbose_name='Fecha Baja')),
                ('tipo_prov', models.CharField(max_length=15, null=True)),
                ('monto_pu', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('motivo_pu', models.TextField(null=True)),
                ('renovacion', models.DateTimeField(max_length=23, null=True)),
                ('inscripcion', models.DateTimeField(max_length=23, null=True)),
                ('solicito_pu', models.CharField(max_length=25, null=True)),
                ('periodo_pu', models.CharField(max_length=15, null=True)),
                ('up', models.CharField(max_length=6, null=True)),
                ('autorizado', models.CharField(max_length=35, null=True)),
                ('curp', models.CharField(max_length=20, null=True)),
                ('captura', models.CharField(max_length=1, null=True)),
                ('solicitar', models.CharField(max_length=1, null=True)),
                ('cat', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('subcat', models.CharField(max_length=10, null=True)),
                ('f_activacion', models.DateTimeField(max_length=23, null=True)),
                ('rep_legal', models.CharField(max_length=100, null=True)),
                ('persona', models.CharField(max_length=10, null=True)),
                ('tipo_alta', models.CharField(max_length=15, null=True)),
                ('num_ext', models.CharField(max_length=10, null=True)),
                ('num_int', models.CharField(max_length=10, null=True)),
                ('calle_notif', models.CharField(max_length=100, null=True)),
                ('next_notif', models.CharField(max_length=10, null=True)),
                ('nint_notif', models.CharField(max_length=10, null=True)),
                ('colonia_notif', models.CharField(max_length=50, null=True)),
                ('ciudad_notif', models.CharField(max_length=50, null=True)),
                ('pais_notif', models.CharField(max_length=50, null=True)),
                ('zip_notif', models.CharField(max_length=52, null=True)),
                ('observaciones2', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('numero_contrato', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Contrato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Inicial')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Total')),
                ('fondo', models.CharField(choices=[('MHA', 'MHA'), ('Genshin', 'Genshin')], default='MHA', max_length=50, verbose_name='Fondo')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de Contrato')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Terminacion')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado'), ('En proceso', 'En Proceso')], default='Activo', max_length=50, verbose_name='Estado')),
                ('label', models.IntegerField(default=0, verbose_name='Etiqueta')),
                ('tipo', models.TextField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Licencia', 'Licencia'), ('Mantenimiento', 'Mantenimiento')], default='Servicio', max_length=50, verbose_name='Tipo de Contrato')),
                ('tipo_1', models.CharField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Licencia', 'Licencia'), ('Mantenimiento', 'Mantenimiento')], default='Servicio', max_length=50, verbose_name='Tipo_1')),
                ('tipo_2', models.CharField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Licencia', 'Licencia'), ('Mantenimiento', 'Mantenimiento')], default='Servicio', max_length=50, verbose_name='Tipo_2')),
                ('id_proveedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Contratos_ID', to='captura_contrato.proveedor', verbose_name='ID_proveedor')),
            ],
        ),
    ]
