# Generated by Django 5.2.6 on 2025-09-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Proveedor')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Nombre Proveedor')),
                ('estatus', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=50, verbose_name='Estatus')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('tipo', models.CharField(choices=[('Gasto Corriente', 'Gasto Corriente'), ('Proyecto', 'Proyecto')], default='Gato Corriente', max_length=50, verbose_name='Tipo de Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('numero_contrato', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Contrato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Inicial')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Total')),
                ('fondo', models.CharField(choices=[('MHA', 'MHA'), ('Genshin', 'Genshin')], default='MHA', max_length=50, verbose_name='Fondo')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de Contrato')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Terminacion')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado'), ('En proceso', 'En Proceso')], default='Activo', max_length=50, verbose_name='Estado')),
                ('label', models.IntegerField(default=0, verbose_name='Etiqueta')),
                ('tipo', models.CharField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Licencia', 'Licencia'), ('Mantenimiento', 'Mantenimiento')], default='Servicio', max_length=50, verbose_name='Tipo de Contrato')),
                ('tipo_1', models.CharField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Licencia', 'Licencia'), ('Mantenimiento', 'Mantenimiento')], default='Servicio', max_length=50, verbose_name='Tipo_1')),
                ('tipo_2', models.CharField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Licencia', 'Licencia'), ('Mantenimiento', 'Mantenimiento')], default='Servicio', max_length=50, verbose_name='Tipo_2')),
                ('id_proveedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Contratos_ID', to='captura_contrato.proveedor', verbose_name='ID_proveedor')),
                ('proveedor', models.ForeignKey(default='Shoto', max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='Contratos_name_Prov', to='captura_contrato.proveedor', verbose_name='f-Nombre del Proveedor')),
            ],
        ),
    ]
