# Generated by Django 5.2.6 on 2025-11-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura_contrato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='proveedor',
        ),
    ]
