# Generated by Django 5.2.6 on 2025-11-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura_contrato', '0002_remove_contrato_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='area',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='area_fax',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='autorizado',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_cuenta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_tipo_cuenta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='calle_notif',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='captura',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cat',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad_notif',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='colonia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='colonia_notif',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_pago',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='curp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='domicilio_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='f_activacion',
            field=models.DateTimeField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fax',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_alta',
            field=models.DateTimeField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_estatus',
            field=models.DateTimeField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_modificacion',
            field=models.DateTimeField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='forma_pago',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='inscripcion',
            field=models.DateTimeField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='monto_pu',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='motivo_pu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='next_notif',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nint_notif',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='num_empleado',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='num_ext',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='num_int',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais_notif',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='periodo_pu',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='persona',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='renovacion',
            field=models.DateTimeField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rep_legal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='solicitar',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='solicito_pu',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='subcat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='temporal',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_alta',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_prov',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='up',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario_alta',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario_modificacion',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='zip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='zip_notif',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.TextField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Licencia', 'Licencia'), ('Mantenimiento', 'Mantenimiento')], default='Servicio', max_length=50, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estatus',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C')], default='A', max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, max_length=23, null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False, verbose_name='ID Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.TextField(choices=[('', ''), ('BECARIO', 'BECARIO'), ('CONTRATISTA', 'CONTRATISTA'), ('DAP', 'DAP'), ('EMPLEADO', 'EMPLEADO'), ('ORGANISMOS', 'ORGANISMOS'), ('PAGO PASIVO', 'PAGO PASIVO'), ('PAGO UNICO', 'PAGO UNICO'), ('PROVEEDORES', 'PROVEEDORES'), ('SEGURO VIDA', 'SEGURO VIDA')], default=' ', max_length=50, null=True, verbose_name='Tipo Proveedor'),
        ),
    ]
