# Generated by Django 5.2.6 on 2025-11-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura_contrato', '0003_proveedor_area_proveedor_area_fax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='rfc',
            new_name='rfc_shoto',
        ),
    ]
