# Generated by Django 5.2.6 on 2025-11-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura_contrato', '0004_rename_rfc_proveedor_rfc_shoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='rfc_shoto',
            new_name='rfc_prueba',
        ),
    ]
